<?php

/**
 * @file
 * Primary module hooks for Access Controller module.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form().
 */
function access_controller_form($form, FormStateInterface $form_state) {
  $form['access_control'] = \Drupal::formBuilder()->getForm('Drupal\access_controller\Form\SettingsForm');
  return $form;
}

/**
 * Implements hook_node_access().
 */
function access_controller_node_access(NodeInterface $node, $op, AccountInterface $account) {
  if ($op == 'view') {
    $accessControlService = \Drupal::service('custom_access_control.access_control_service');
    return $accessControlService->checkNodeAccess($node);
  }
  return NULL;
}
