# Schema for the configuration files of the newdropdown module.
newdropdown.settings:
  type: config_object
  label: 'newdropdown settings'
  mapping:
    example:
      type: string
      label: 'Example'
