<?php

/**
 * @file
 * Primary module hooks for mail_task module.
 */


use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_mail().
 */
function mail_task_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];

  switch ($key) {
    case 'create_page':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Node created: @title', ['@title' => $params['node_title']], $options);
      $message['body'][] = $params['body'];
      break;
  }
}

/**
 * Implements hook_entity_insert().
 */
function mail_task_entity_insert(EntityInterface $entity) {
  $mailManager = \Drupal::service('plugin.manager.mail');

  $module = 'mail_task';

  $key = 'create_page';
  $to = \Drupal::currentUser()->getEmail();
  $config = \Drupal::config('mail_task.settings');
  $message = $config->get('subject');
  $text = $config->get('text')['value'];
  $token_service = \Drupal::token();
  $sub_message = $token_service->replace($message, ['node' => $entity], ['clear' => TRUE]);
  $sub_text = $token_service->replace($text, ['node' => $entity], ['clear' => TRUE]);
  $params['subject'] = $sub_message;
  $params['body'] = $sub_text;
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = TRUE;

  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  if ($result['result'] !== TRUE) {

    \Drupal::messenger()->addMessage(t('There was a problem sending your message and it was not sent'), 'error');
  }
  else {

    \Drupal::messenger()->addMessage(t('Your mail has been sent.'), 'status');
  }

}

/**
 * Implements hook_mail_alter().
 */
function mail_task_mail_alter(&$message) {
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
}
